# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k9oBlhNGLeG8o-LrlyaU8U5jlftPBXXN

df.groupby(['Alone'])['Survived'].mean()
df[['Alone','Fare']].corr()
"""

import pandas as pd
import numpy as np
df = pd.DataFrame(pd.read_csv('/content/sample_data/train.csv'))
df.head()
df.shape
(891,12)

x=df.isnull().sum()
drop_col=x[x>(35/100* df.shape[0])]

df.drop(drop_col.index,axis=1, inplace=True)
df.isnull().sum()

df.fillna(df.mean(), inplace=True)
df.isnull().sum()

df['Embarked'].describe()
df['Embarked'].fillna('S', inplace=True)
df.isnull().sum()

df.corr()
df['FamilySize']= df['SibSp']+df['Parch']
df.drop(['SibSp','Parch'], axis=1, inplace=True)
df.corr()

df['Alone']=[0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean()
df[['Alone','Fare']].corr()

df['Sex'] =[0 if df['Sex'][i]=='male' else 1 for i in df.index] 
df.groupby(['Sex'])['Survived'].mean()

df.groupby(['Embarked'])['Survived'].mean()

""" **Conclusion**


*   Female passengers were prioritized over men.

*   People with high class or rich people have higher survival rate than others. The hierarchy might have been followed while saving the passengers.

*  Passengers travelling with their family have higher survival rate.

*   Passengers who borded the ship at Cherbourg, survived more in proportion than the others.

"""